#!/bin/bash
# scripts/verify_github.sh
# Verifies actual GitHub state against .github/governance.yaml.
# Outputs: GITHUB_AUDIT.md (human) and governance-report.json (machine).

set -e

SPEC_FILE=".github/governance.yaml"
AUDIT_FILE="GITHUB_AUDIT.md"
REPORT_FILE="governance-report.json"
COMPLIANCE_FAILED=0

# Drift Classification Levels
LEVEL_INFO="INFO"
LEVEL_WARN="WARN"
LEVEL_ERROR="ERROR"

# Helper for status printing
pass() { echo -e "\033[1;32m[PASS]\033[0m $1"; }
fail() { echo -e "\033[1;31m[FAIL]\033[0m $1"; COMPLIANCE_FAILED=1; }
warn() { echo -e "\033[1;33m[WARN]\033[0m $1"; }
info() { echo -e "\033[1;34m[INFO]\033[0m $1"; }

# 0. Prerequisite Check
if ! command -v yq &> /dev/null; then echo "yq not found"; exit 2; fi
if ! command -v jq &> /dev/null; then echo "jq not found"; exit 2; fi

# 1. Load Expected State
REPO_NAME=$(yq '.repository.name' "$SPEC_FILE")
REPO_OWNER=$(yq '.repository.owner' "$SPEC_FILE")
REPO="$REPO_OWNER/$REPO_NAME"
SPEC_VERSION=$(yq '.metadata.version' "$SPEC_FILE")

echo "🔎 Verifying Governance for $REPO (Spec v$SPEC_VERSION)"

# 2. Fetch Actual State
repo_json=$(gh repo view "$REPO" --json name,description,isPrivate,hasWikiEnabled,hasDiscussionsEnabled,hasProjectsEnabled,defaultBranchRef,squashMergeAllowed,mergeCommitAllowed,rebaseMergeAllowed,deleteBranchOnMerge || exit 3)

# 3. Validation Logic
results_json="{ \"schemaVersion\": \"1\", \"generatedAt\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\", \"spec_version\": \"$SPEC_VERSION\", \"checks\": [] }"

add_check() {
  local id=$1
  local status=$2
  local level=$3
  local message=$4
  results_json=$(echo "$results_json" | jq ".checks += [{\"id\": \"$id\", \"status\": \"$status\", \"level\": \"$level\", \"message\": \"$message\"}]")
  
  if [[ "$status" == "FAIL" ]]; then
    if [[ "$level" == "$LEVEL_ERROR" ]]; then fail "$id: $message"; 
    elif [[ "$level" == "$LEVEL_WARN" ]]; then warn "$id: $message";
    else info "$id: $message"; fi
  else
    pass "$id: $message"
  fi
}

# Critical Checks (ERROR on fail)
check_repo_property() {
  local id=$1
  local expected=$2
  local actual=$3
  local level=$4
  if [[ "$expected" == "$actual" ]]; then
    add_check "$id" "PASS" "$LEVEL_INFO" "$actual"
  else
    add_check "$id" "FAIL" "$level" "Expected $expected, got $actual"
  fi
}

check_repo_property "repo.visibility" "$(yq '.repository.visibility' "$SPEC_FILE")" "$([[ $(echo "$repo_json" | jq -r '.isPrivate') == "false" ]] && echo "public" || echo "private")" "$LEVEL_ERROR"
check_repo_property "repo.description" "$(yq '.repository.description' "$SPEC_FILE")" "$(echo "$repo_json" | jq -r '.description')" "$LEVEL_WARN"
check_repo_property "repo.wiki" "$(yq '.repository.features.wiki' "$SPEC_FILE")" "$(echo "$repo_json" | jq -r '.hasWikiEnabled')" "$LEVEL_WARN"

# Branch Protections (ERROR on fail)
check_branch_protection() {
  local branch=$1
  info "Checking $branch protection..."
  actual_protection=$(gh api "repos/$REPO/branches/$branch/protection" 2>/dev/null || echo "{}")
  expected_protection=$(yq -o=json ".branches.$branch.protection" "$SPEC_FILE")
  
  actual_reviews=$(echo "$actual_protection" | jq -r '.required_pull_request_reviews.required_approving_review_count // 0' 2>/dev/null | grep -E '^[0-9]+$' || echo "0")
  expected_reviews=$(echo "$expected_protection" | jq -r '.required_pull_request_reviews.required_approving_review_count // 0' 2>/dev/null | grep -E '^[0-9]+$' || echo "0")
  
  if [[ "$actual_reviews" -eq "$expected_reviews" ]]; then
    add_check "branch.$branch.reviews" "PASS" "$LEVEL_INFO" "$actual_reviews"
  else
    add_check "branch.$branch.reviews" "FAIL" "$LEVEL_ERROR" "Expected $expected_reviews reviews, got $actual_reviews"
  fi
}

check_branch_protection "main"
check_branch_protection "develop"

# 4. Generate Audit Files
echo "$results_json" | jq '.' > "$REPORT_FILE"

cat > "$AUDIT_FILE" <<EOF
# GitHub Repository Audit Snapshot — $REPO

**Governance Spec**: v$SPEC_VERSION
**Verification Date**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
**Audit Git SHA**: $(git rev-parse HEAD 2>/dev/null || echo "N/A")
**Compliance Status**: $([[ $COMPLIANCE_FAILED -eq 0 ]] && echo "PASS" || echo "FAIL")

## Summary
$(echo "$results_json" | jq -r '.checks[] | "- [" + (if .status == "PASS" then "x" else " " end) + "] **" + .id + "** (" + .level + "): " + .message')

---
*Generated by scripts/verify_github.sh*
EOF

if [[ $COMPLIANCE_FAILED -eq 0 ]]; then
    pass "Governance verified."
    exit 0
else
    fail "Governance drift detected (ERROR level)."
    exit 1
fi
