#!/bin/bash
# scripts/verify_github.sh
# Verifies actual GitHub state against .github/governance.yaml.
# Outputs: GITHUB_AUDIT.md (human) and governance-report.json (machine).

set -e

SPEC_FILE=".github/governance.yaml"
AUDIT_FILE="GITHUB_AUDIT.md"
REPORT_FILE="governance-report.json"
COMPLIANCE_FAILED=0

# Helper for status printing
pass() { echo -e "\033[1;32m[PASS]\033[0m $1"; }
fail() { echo -e "\033[1;31m[FAIL]\033[0m $1"; COMPLIANCE_FAILED=1; }
info() { echo -e "\033[1;34m[INFO]\033[0m $1"; }

# 0. Prerequisite Check
if ! command -v yq &> /dev/null; then echo "yq not found"; exit 2; fi
if ! command -v jq &> /dev/null; then echo "jq not found"; exit 2; fi

# 1. Load Expected State
REPO_NAME=$(yq '.repository.name' "$SPEC_FILE")
REPO_OWNER=$(yq '.repository.owner' "$SPEC_FILE")
REPO="$REPO_OWNER/$REPO_NAME"
SPEC_VERSION=$(yq '.version' "$SPEC_FILE")

echo "🔎 Verifying Governance for $REPO (Spec v$SPEC_VERSION)"

# 2. Fetch Actual State
repo_json=$(gh repo view "$REPO" --json name,description,isPublic,hasWikiEnabled,hasDiscussionsEnabled,hasProjectsEnabled,defaultBranchRef,squashMergeAllowed,mergeCommitAllowed,rebaseMergeAllowed,deleteBranchOnMerge || exit 3)

# 3. Validation Logic
results_json="{ \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\", \"spec_version\": \"$SPEC_VERSION\", \"checks\": [] }"

add_check() {
  local name=$1
  local status=$2
  local message=$3
  results_json=$(echo "$results_json" | jq ".checks += [{\"name\": \"$name\", \"status\": \"$status\", \"message\": \"$message\"}]")
}

check_repo_property() {
  local prop=$1
  local expected=$2
  local actual=$3
  if [[ "$expected" == "$actual" ]]; then
    pass "Repo $prop: $actual"
    add_check "repo_$prop" "pass" "$actual"
  else
    fail "Repo $prop: Expected $expected, got $actual"
    add_check "repo_$prop" "fail" "Expected $expected, got $actual"
  fi
}

check_repo_property "visibility" "$(yq '.repository.visibility' "$SPEC_FILE")" "$([[ $(echo "$repo_json" | jq -r '.isPublic') == "true" ]] && echo "public" || echo "private")"
check_repo_property "wiki" "$(yq '.repository.features.wiki' "$SPEC_FILE")" "$(echo "$repo_json" | jq -r '.hasWikiEnabled')"
check_repo_property "discussions" "$(yq '.repository.features.discussions' "$SPEC_FILE")" "$(echo "$repo_json" | jq -r '.hasDiscussionsEnabled')"

# Branch Protections
check_branch_protection() {
  local branch=$1
  info "Checking $branch protection..."
  actual_protection=$(gh api "repos/$REPO/branches/$branch/protection" --silent || echo "{}")
  expected_protection=$(yq -o=json ".branches.$branch.protection" "$SPEC_FILE")
  
  # Basic comparison of key fields
  actual_reviews=$(echo "$actual_protection" | jq -r '.required_pull_request_reviews.required_approving_review_count // 0')
  expected_reviews=$(echo "$expected_protection" | jq -r '.required_pull_request_reviews.required_approving_review_count // 0')
  
  if [[ "$actual_reviews" -eq "$expected_reviews" ]]; then
    pass "$branch: Required reviews match ($actual_reviews)"
    add_check "${branch}_reviews" "pass" "$actual_reviews"
  else
    fail "$branch: Required reviews mismatch (Expected $expected_reviews, got $actual_reviews)"
    add_check "${branch}_reviews" "fail" "Expected $expected_reviews, got $actual_reviews"
  fi
}

check_branch_protection "main"
check_branch_protection "develop"

# 4. Generate Audit Files
echo "$results_json" | jq '.' > "$REPORT_FILE"

cat > "$AUDIT_FILE" <<EOF
# GitHub Repository Audit Snapshot — $REPO

**Governance Spec**: v$SPEC_VERSION
**Verification Date**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
**Audit Git SHA**: $(git rev-parse HEAD 2>/dev/null || echo "N/A")
**Compliance Status**: $([[ $COMPLIANCE_FAILED -eq 0 ]] && echo "PASS" || echo "FAIL")

## Summary
$(echo "$results_json" | jq -r '.checks[] | "- [" + (if .status == "pass" then "x" else " " end) + "] **" + .name + "**: " + .message')

---
*Generated by scripts/verify_github.sh*
EOF

if [[ $COMPLIANCE_FAILED -eq 0 ]]; then
    pass "Governance verified."
    exit 0
else
    fail "Governance drift detected."
    exit 1
fi
