name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@0c4977f5a9e58c2140cd0bb9ba3996540d447ecd # v5.0.0
        with:
          go-version: '1.22.x'
      - run: go test -v -race ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.5
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@0c4977f5a9e58c2140cd0bb9ba3996540d447ecd # v5.0.0
        with:
          go-version: '1.22.x'
      - run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - run: govulncheck ./...
